instagram/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root :to => "home#index"

  match 'auth/:provider/callback', to: 'sessions#create', via: :get
  match 'auth/failure', to: redirect('/'), via: :get
  match 'signout', to: 'sessions#destroy', as: 'signout', via: :get

  resources :users
  resources :locations
  get '/search' => 'home#index'

end

instagram/app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode
end

instagram/app/models/user.rb
class User < ActiveRecord::Base
	 def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider 
        user.uid      = auth.uid
        user.name     = auth.info.name
        user.oauth_token = auth.credentials.token
        #user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
end

instagram/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

instagram/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @location = Location.new
  	@instagram = Instagram.user_recent_media("1792475136")
    client = Instagram.client(:access_token => session[:access_token])
    unless params[:q].blank?
      tags = client.tag_search(params[:q])
      @tag1 = client.tag_recent_media(tags[0].name, count: 100)
      @max_tag_id1 = @tag1.pagination.next_max_tag_id
      @tag2 = client.tag_recent_media(tags[0].name,count: 100, max_id: @max_tag_id1) unless @max_tag_id1.nil?
      @max_tag_id2 = @tag2.pagination.next_max_tag_id
      @tag3 = client.tag_recent_media(tags[0].name,count: 100, max_id: @max_tag_id2) unless @max_tag_id2.nil?
      @max_tag_id3 = @tag3.pagination.next_max_tag_id
      @tag4 = client.tag_recent_media(tags[0].name,count: 100, max_id: @max_tag_id3) unless @max_tag_id3.nil?
      @max_tag_id4 = @tag4.pagination.next_max_tag_id
      @count=  tags[0].media_count
    else
  	  @tag1 = client.tag_recent_media('worldcup2015')
      @tag2 = client.tag_recent_media('teamindia')
      @tag3 = client.tag_recent_media('nzvsaus')
      @tag4 = client.tag_recent_media('indiavsaus')
    end
  end
end

instagram/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    
    @locations = Location.all
    
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    client = Instagram.client(:access_token => session[:access_token])
    @media=client.media_search(@location.latitude, @location.longitude, options = {:count => 100})
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

instagram/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

instagram/app/helpers/locations_helper.rb
module LocationsHelper
end

instagram/app/views/home/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
    <%= submit_tag("Location Search") %>
  </div>
<% end %>

instagram/app/views/home/index.html.erb
<h1>Search Location Pics</h1>

<%= render 'form' %>
<br>
<br>
<% @instagram.each do |instagram| %>

    <%= image_tag instagram.images.standard_resolution.url %>

<% end %>
<br>
<h1>Searched Tag Media</h1>
<p>Tag Counts</p><%= @count%>
<br>
<% @tag1.each do |tag| %>

    <%= image_tag tag.images.standard_resolution.url %>

<% end %>
<% @tag2.each do |tag| %>

    <%= image_tag tag.images.standard_resolution.url %>

<% end %>
<% @tag3.each do |tag| %>

    <%= image_tag tag.images.standard_resolution.url %>

<% end %>
<% @tag4.each do |tag| %>

    <%= image_tag tag.images.standard_resolution.url %>

<% end %>

instagram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>

<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Instagram", "/auth/instagram", id: "sign_in" %>
  <% end %>
</div>
<meta charset="utf-8"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<br>
<br>
<h1>Search HashTag Pics</h1>
<%= form_tag("/search", :method => "get") do %>
    <p> HashTag </p>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Tag Search") %>
<% end %>
<br>
<%= yield %>

</body>
</html>

instagram/app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %>

instagram/app/views/locations/index.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :address %>
    <%= submit_tag("Location Search") %>
  </div>
<% end %>

instagram/app/views/locations/new.html.erb
<h1>Search Location</h1>

<%= render 'form' %>

instagram/app/views/locations/show.html.erb
<%= render 'form' %>





<%= link_to 'Edit', edit_location_path(@location) %>

<br>
<p>Location Images</p>
<br>
<% @media.each do |media| %>

    <%= image_tag media.images.standard_resolution.url %>

<% end %>